name: Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Firebase credentials file
        run: echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > src/main/resources/firebase-credentials.properties

      - name: Create secrets properties file
        run: |
          cat <<EOT > src/main/resources/secrets.properties
          spring.datasource.url=${{ secrets.DATABASE_URL }}
          spring.datasource.username=${{ secrets.DATABASE_USERNAME }}
          spring.datasource.password=${{ secrets.DATABASE_PASSWORD }}
          EOT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest